### ISSUE TITLE
Other zones?

### ISSUE THREAD

**Issue by veltman** [gka/d3-geo-state-planes#1]
Interested in a PR with other zones per state? Or do you want to keep it state-level?

https://github.com/veltman/d3-stateplane

**Comment by dakoop** [comment]
Related: How was the default zone for each state chosen (most northern/eastern?), and are these the appropriate projections for statewide maps? For example, Wisconsin established a tmerc for statewide coordinates while its three state planes are lcc.

**Comment by gka** [comment]
@dakoop for now I just went with the definitions I found in ProPublica's [stateface font](https://github.com/propublica/stateface/blob/master/tools/state-planes.rb), but open to suggestions.

@veltman the other zones might be interesting, too, but maybe that would better fit into something like `d3.geo.espg` or `d3.geo.proj4`. in this case, state-level made sense bc it's something people need all the time, and the geographic boundaries are kind of fixed.
